[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kangengine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "imageio>=2.37",
    "imageio-ffmpeg>=0.6",
    "numpy>=1.26",
    "torch>=1.9.1",
]

[project.optional-dependencies]
docs = [
    "sphinx>=8",
    "myst-parser>=4",
    "sphinx-autodoc-typehints>=3",
    "sphinx-copybutton>=0.5",
    "sphinx-sitemap>=2.6",
    "furo>=2024.8.6",
]
mimickit = [
    "gymnasium",
    "pyyaml",
]
mimickit-full = [
    "gymnasium",
    "pyyaml",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["kangengine*"]

[tool.setuptools.package-data]
kangengine = [
    "_kangengine.so",
    "**/*.pyi",
    "py.typed",
    "assets/**/*",
]

[tool.setuptools.exclude-package-data]
kangengine = ["assets/external/**/*"]

[tool.ruff]
line-length = 88
target-version = "py312"
extend-exclude = ["kangengine/assets"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]

[tool.ruff.lint.per-file-ignores]
"kangengine/__init__.py" = ["E402"]
"kangengine/input/__init__.py" = ["E402"]
"kangengine/physics/__init__.py" = ["F403"]

[tool.ruff.format]
docstring-code-format = true

[dependency-groups]
dev = [
    "ruff>=0.16.1",
]
