[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kangengine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["numpy>=1.26", "torch>=1.9.1"]

[project.optional-dependencies]
docs = [
    "sphinx>=8",
    "myst-parser>=4",
    "sphinx-autodoc-typehints>=3",
    "sphinx-copybutton>=0.5",
    "furo>=2024.8.6",
]
mimickit = [
    "gymnasium",
    "pyyaml",
]
mimickit-video = [
    "moviepy",
]
mimickit-full = [
    "gymnasium",
    "moviepy",
    "pyyaml",
]

[tool.setuptools]
packages = ["kangengine", "kangengine.utils"]
include-package-data = true

[tool.setuptools.package-data]
kangengine = [
    "_kangengine.so",
    "assets/**/*",
]
